# Generated by Django 3.1.2 on 2020-11-30 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyboard', '0002_auto_20201130_2246'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studyboard',
            table='studyboard_post',
        ),
    ]
