# Generated by Django 3.1.2 on 2020-11-30 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyboard', '0003_auto_20201130_2249'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studyboard',
            table='studyboard_postlist',
        ),
    ]
