# Generated by Django 3.1.2 on 2020-12-11 22:41

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('studyboard', '0005_auto_20201201_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyboard',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
