# Generated by Django 3.1.2 on 2020-11-30 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_auto_20201130_2226'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notice',
            table='notice',
        ),
    ]
