# Generated by Django 3.1.2 on 2020-12-01 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_auto_20201130_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='description',
        ),
    ]
